AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  HelloWorldFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ./src
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
